import Head from 'next/head'
import Navbar from "components/Navbar/Navbar"
import LandingSection from "../components/LandingSection/LandingSection";


export default function Home() {
    return (
        <div >
            <Head>
                {/* eslint-disable-next-line react/no-unescaped-entities */}
                <title>Cakes n Cookie's</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                <Navbar/>
                <LandingSection/>
            </main>
        </div>
    )
}
